# Generated by Django 3.1 on 2020-10-31 12:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tuition/images'),
        ),
    ]
